### ISSUE TITLE
Deliver step failing

### ISSUE THREAD

**Issue by alcarvalho** [bitrise-io/bitrise.io#15]
Deliver step is failing with unrecognized option `--skip-deploy`:

Here is the complete log for the step:

```text
+------------------------------------------------------------------------------+
| (7) deploy-to-itunesconnect-deliver                                          |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-deliver                                          |
| version: 2.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| time: 2015-10-14T18:02:46-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
 (i) TestFlight beta deploy type flag: --skip-deploy
# Setup
 (i) deliver NOT yet installed, attempting install...
 -> installing with RVM
Successfully installed addressable-2.3.8
Successfully installed fastimage-1.6.8
Successfully installed method_source-0.8.2
Successfully installed slop-3.6.0
Successfully installed coderay-1.1.0
Successfully installed pry-0.10.3
Successfully installed faraday-0.9.2
Successfully installed multi_xml-0.5.5
Successfully installed credentials_manager-0.9.0
Successfully installed spaceship-0.12.0
Successfully installed xpath-2.0.0
Successfully installed rack-test-0.6.3
Successfully installed capybara-2.4.4
Successfully installed websocket-extensions-0.1.2
Building native extensions.  This could take a while...
invalid options: -SNw2
(invalid options are ignored)
Successfully installed websocket-driver-0.6.2
Successfully installed multi_json-1.11.2
Successfully installed cliver-0.3.2
Successfully installed poltergeist-1.5.1
Successfully installed phantomjs-1.9.8.0
Successfully installed excon-0.45.4
Successfully installed babosa-1.0.2
Successfully installed fastlane_core-0.22.2
Successfully installed deliver-1.3.2
Parsing documentation for addressable-2.3.8
Installing ri documentation for addressable-2.3.8
Parsing documentation for fastimage-1.6.8
Installing ri documentation for fastimage-1.6.8
Parsing documentation for method_source-0.8.2
Installing ri documentation for method_source-0.8.2
Parsing documentation for slop-3.6.0
Installing ri documentation for slop-3.6.0
Parsing documentation for coderay-1.1.0
Installing ri documentation for coderay-1.1.0
Parsing documentation for pry-0.10.3
Installing ri documentation for pry-0.10.3
Parsing documentation for faraday-0.9.2
Installing ri documentation for faraday-0.9.2
Parsing documentation for multi_xml-0.5.5
Installing ri documentation for multi_xml-0.5.5
Parsing documentation for credentials_manager-0.9.0
Installing ri documentation for credentials_manager-0.9.0
Parsing documentation for spaceship-0.12.0
Installing ri documentation for spaceship-0.12.0
Parsing documentation for xpath-2.0.0
Installing ri documentation for xpath-2.0.0
Parsing documentation for rack-test-0.6.3
Installing ri documentation for rack-test-0.6.3
Parsing documentation for capybara-2.4.4
Installing ri documentation for capybara-2.4.4
Parsing documentation for websocket-extensions-0.1.2
Installing ri documentation for websocket-extensions-0.1.2
Parsing documentation for websocket-driver-0.6.2
Installing ri documentation for websocket-driver-0.6.2
Parsing documentation for multi_json-1.11.2
Installing ri documentation for multi_json-1.11.2
Parsing documentation for cliver-0.3.2
Installing ri documentation for cliver-0.3.2
Parsing documentation for poltergeist-1.5.1
Installing ri documentation for poltergeist-1.5.1
Parsing documentation for phantomjs-1.9.8.0
Installing ri documentation for phantomjs-1.9.8.0
Parsing documentation for excon-0.45.4
Installing ri documentation for excon-0.45.4
Parsing documentation for babosa-1.0.2
Installing ri documentation for babosa-1.0.2
Parsing documentation for fastlane_core-0.22.2
Installing ri documentation for fastlane_core-0.22.2
Parsing documentation for deliver-1.3.2
Installing ri documentation for deliver-1.3.2
Done installing documentation for addressable, fastimage, method_source, slop, coderay, pry, faraday, multi_xml, credentials_manager, spaceship, xpath, rack-test, capybara, websocket-extensions, websocket-driver, multi_json, cliver, poltergeist, phantomjs, excon, babosa, fastlane_core, deliver after 64 seconds
23 gems installed
 (i) Setup took 80 seconds to complete
# Deploy
**Note:** if your password
contains special characters
and you experience problems, please
consider changing your password
to something with only
alphanumeric characters.
**Be advised** that this
step uses a well maintained, open source tool which
uses *undocumented and unsupported APIs* (because the current
iTunes Connect platform does not have a documented and supported API)
to perform the deployment.
This means that when the API changes
**this step might fail until the tool is updated**.
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/command.rb:164:in `parse_options_and_call_procs': invalid option: --skip-deploy (OptionParser::InvalidOption)
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:84:in `run'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/deliver-1.3.2/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/gems/deliver-1.3.2/bin/deliver:5:in `'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/bin/deliver:23:in `load'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/bin/deliver:23:in `
'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `
'
 [!] Error description: Deploy failed!
     (i) Exit code was: 1
 (i) Calling cleanup function before exit
```

**Comment by viktorbenei** [comment]
Please migrate this issue to the related step's issue tracker: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/issues

*The issue seems to be that `deliver` changed the test flight submission flag syntax recently, they replaced the "don't send" option with a "do send" `--submit_for_review`*

Please create a new issue at the step, so we can properly track it's state and you get notification when it's fixed.

**Comment by alcarvalho** [comment]
Thanks for the quick reply.

At first I thought I should create the issue on the step's repository, but when I checked the "contact" page on Bitrise, I was directed to report it here. Maybe this should be explained on that page.

**Comment by viktorbenei** [comment]
You're right @alcarvalho and thanks for moving the issue! We'll think about making this more clear.
