### ISSUE TITLE
Bitrise new project validation fails at CocoaPods install if pod used from git submodule

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise.io#3]
From the logs it seems that the setup is correct, the repository is cloned with all it's submodules, but then the CocoaPods install step of the validation fails with an error:

	Fetching external sources
	-> Fetching podspec for `APodName` from `pod-submodule-folder`
	[!] No podspec found for `APodName` in `pod-submodule-folder`

	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/path_source.rb:16:in `block in fetch'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/path_source.rb:13:in `fetch'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:323:in `each'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:189:in `analyze'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:90:in `install!'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:101:in `run'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/lib/cocoapods/command.rb:46:in `run'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.36.1/bin/pod:44:in `<top (required)>'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/pod:23:in `load'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/pod:23:in `<main>'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
	 [!] Error description: Failed to pod install

A simple `pod install` actually works on a repository like this, but the pod installer step - used in the validation workflow - fails.

Sample repository for reproducing the issue: https://github.com/mvoong/BitRiseTest

**Comment by viktorbenei** [comment]
Proposed fix: https://github.com/bitrise-io/steps-cocoapods-and-repository-validator/pull/4
Under testing

**Comment by viktorbenei** [comment]
Fixed and live on Bitrise.io
