### ISSUE TITLE
iOS Build

### ISSUE THREAD

**Issue by ryanherman** [bitrise-io/bitrise.io#68]
I get this error message that I never got before:
#<RuntimeError: Build failed>
--- Stack trace: ---
["/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise420514183/step_src/xamarin-builder/builder.rb:118:in `block in build'", "/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise420514183/step_src/xamarin-builder/builder.rb:111:in `each'", "/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise420514183/step_src/xamarin-builder/builder.rb:111:in `build'", "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise420514183/step_src/step.rb:315:in `<main>'"]

**Comment by ryanherman** [comment]
I selected the wrong stack.
