### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by spolyakov-4xxi** [bitrise-io/bitrise.io#84]
In the end of some step 
```
Success
|                                                                              |
+----+--------------------------------------------------------------+----------+
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x3ad360, 0xc42035bc70)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.HandleAction.func1(0xc4201fd958)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/app.go:478 +0x247
panic(0x3ad360, 0xc42035bc70)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
strings.Repeat(0x408ef0, 0x1, 0xfffffffffffffffe, 0x2, 0x2)
	/usr/local/Cellar/go/1.7.1/libexec/src/strings/strings.go:420 +0x49
github.com/bitrise-io/bitrise/bitrise.getRunningStepFooterMainSection(0xc4202d63a0, 0x9, 0xc420109eb0, 0xf, 0xc4202d6388, 0x5, 0xc4202d63b0, 0x5, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/bitrise/print.go:246 +0x640
github.com/bitrise-io/bitrise/bitrise.PrintRunningStepFooter(0xc4202d63a0, 0x9, 0xc420109eb0, 0xf, 0xc4202d6388, 0x5, 0xc4202d63b0, 0x5, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/bitrise/print.go:515 +0x3ed
github.com/bitrise-io/bitrise/cli.activateAndRunSteps.func1(0xc4202d6eb0, 0xc4202d6ee0, 0xc4202d6f10, 0xc4202d6f40, 0xc4202d6f70, 0xc4202d6fa0, 0xc4202eb020, 0xc4202d2a40, 0x31, 0xc4202d8ed0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:517 +0x3a9
github.com/bitrise-io/bitrise/cli.activateAndRunSteps(0xc4201085c8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:798 +0x1314
github.com/bitrise-io/bitrise/cli.runWorkflow(0xc4201085c8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:810 +0x1e7
github.com/bitrise-io/bitrise/cli.activateAndRunWorkflow(0xc4201085c8, 0x7, 0xc4201085c8, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:832 +0x33b
github.com/bitrise-io/bitrise/cli.runWorkflowWithConfiguration(0xecf9e7740, 0x29e9172d, 0x5e35c0, 0xc4201085c8, 0x7, 0xc420109d28, 0x5, 0xc420063740, 0x31, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run_util.go:935 +0x740
github.com/bitrise-io/bitrise/cli.runAndExit(0xc420109d28, 0x5, 0xc420063740, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run.go:106 +0x122
github.com/bitrise-io/bitrise/cli.run(0xc42009ac80, 0x0, 0x0)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/run.go:215 +0x94c
reflect.Value.call(0x39bec0, 0x446d50, 0x13, 0x4093eb, 0x4, 0xc4201fd918, 0x1, 0x1, 0x11b208, 0x3ff300, ...)
	/usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x39bec0, 0x446d50, 0x13, 0xc4201fd918, 0x1, 0x1, 0x5e4580, 0xc4200ef908, 0x123e76)
	/usr/local/Cellar/go/1.7.1/libexec/src/reflect/value.go:302 +0xa4
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.HandleAction(0x39bec0, 0x446d50, 0xc42009ac80, 0x0, 0x0)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/app.go:487 +0x1e0
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.Command.Run(0x409271, 0x3, 0x0, 0x0, 0x5d81d0, 0x1, 0x1, 0x4121ef, 0x1a, 0x0, ...)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/command.go:191 +0xc3b
github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli.(*App).Run(0xc4200fe000, 0xc42008c000, 0xa, 0xa, 0x0, 0x0)
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/vendor/github.com/urfave/cli/app.go:240 +0x611
github.com/bitrise-io/bitrise/cli.Run()
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/cli/cli.go:157 +0x1b0
main.main()
	/Users/vagrant/go/src/github.com/bitrise-io/bitrise/main.go:6 +0x14
Command failed: exit status 2
```

**Comment by viktorbenei** [comment]
When did this happen? We pushed a fix yesterday (http://blog.bitrise.io/2016/10/24/vm-updates-hotfix-bitrise-cli-update.html)

If it happened since, can you please send us the full log in email?

**Comment by viktorbenei** [comment]
This log seems to be related to the previous Bitrise CLI version, and not to the latest one (which was built with Go 1.7.3 not 1.7.1)

**Comment by spolyakov-4xxi** [comment]
Yes, you right. Last night bild was with 1.4.2, new with 1.4.3 complete successfully, thank you

**Comment by viktorbenei** [comment]
No problem, sorry for the inconvenience, and please report it if you'd see this error again with 1.4.3!
